var window=global;var $CLJS=require("./cljs_env");require("./goog.base.js");require("./cljs.core.js");require("./cljs.tools.reader.js");require("./cljs.tools.reader.edn.js");
var Qg,Sg,Tg,Ug,Xg;Qg=function(a){for(var b=$CLJS.Xb;;)if(a=$CLJS.D(a)){var c=$CLJS.F(a);c=b.a?b.a(c):b.call(null,c);if($CLJS.u(c))return c;a=$CLJS.I(a)}else return null};$CLJS.Rg=function(a){return $CLJS.u(Qg(a))?$CLJS.Tb(function(b,c){return $CLJS.Pc.b($CLJS.u(b)?b:$CLJS.Gc,c)},a):null};Sg=function(a){this.wb=a;this.m=null;this.g=2153775104;this.v=2048};Tg=function(a){a=parseInt(a,10);return $CLJS.zf(isNaN(a))?a:null};
Ug=function(a,b,c,d){if(!(a<=b&&b<=c))throw Error([$CLJS.y.a(d)," Failed:  ",$CLJS.y.a(a),"\x3c\x3d",$CLJS.y.a(b),"\x3c\x3d",$CLJS.y.a(c)].join(""));return b};
Xg=function(a){var b=$CLJS.ue(Vg,a);$CLJS.R(b,0,null);var c=$CLJS.R(b,1,null),d=$CLJS.R(b,2,null),e=$CLJS.R(b,3,null),f=$CLJS.R(b,4,null),h=$CLJS.R(b,5,null),k=$CLJS.R(b,6,null),l=$CLJS.R(b,7,null),m=$CLJS.R(b,8,null),n=$CLJS.R(b,9,null),p=$CLJS.R(b,10,null);if($CLJS.zf(b))throw Error(["Unrecognized date/time syntax: ",$CLJS.y.a(a)].join(""));var r=Tg(c),t=function(){var z=Tg(d);return $CLJS.u(z)?z:1}();a=function(){var z=Tg(e);return $CLJS.u(z)?z:1}();b=function(){var z=Tg(f);return $CLJS.u(z)?z:
0}();c=function(){var z=Tg(h);return $CLJS.u(z)?z:0}();var x=function(){var z=Tg(k);return $CLJS.u(z)?z:0}(),B=function(){a:if($CLJS.N.b(3,$CLJS.K(l)))var z=l;else if(3<$CLJS.K(l))z=l.substring(0,3);else for(z=new $CLJS.ha(l);;)if(3>z.getLength())z=z.append("0");else{z=z.toString();break a}z=Tg(z);return $CLJS.u(z)?z:0}();m=($CLJS.N.b(m,"-")?-1:1)*(60*function(){var z=Tg(n);return $CLJS.u(z)?z:0}()+function(){var z=Tg(p);return $CLJS.u(z)?z:0}());return new $CLJS.W(null,8,5,$CLJS.X,[r,Ug(1,t,12,"timestamp month field must be in range 1..12"),
Ug(1,a,function(){var z=0===(r%4+4)%4&&(0!==(r%100+100)%100||0===(r%400+400)%400);return Wg.b?Wg.b(t,z):Wg.call(null,t,z)}(),"timestamp day field must be in range 1..last day in month"),Ug(0,b,23,"timestamp hour field must be in range 0..23"),Ug(0,c,59,"timestamp minute field must be in range 0..59"),Ug(0,x,$CLJS.N.b(c,59)?60:59,"timestamp second field must be in range 0..60"),Ug(0,B,999,"timestamp millisecond field must be in range 0..999"),m],null)};Sg.prototype.toString=function(){return this.wb};
Sg.prototype.I=function(a,b){return b instanceof Sg&&this.wb===b.wb};Sg.prototype.M=function(a,b){return $CLJS.Y(b,['#uuid "',$CLJS.y.a(this.wb),'"'].join(""))};Sg.prototype.J=function(){null==this.m&&(this.m=$CLJS.Za(this.wb));return this.m};var Wg,Vg;Wg=function(){var a=new $CLJS.W(null,13,5,$CLJS.X,[null,31,28,31,30,31,30,31,31,30,31,30,31],null),b=new $CLJS.W(null,13,5,$CLJS.X,[null,31,29,31,30,31,30,31,31,30,31,30,31],null);return function(c,d){return $CLJS.T.b($CLJS.u(d)?b:a,c)}}();Vg=/(\d\d\d\d)(?:-(\d\d)(?:-(\d\d)(?:[T](\d\d)(?::(\d\d)(?::(\d\d)(?:[.](\d+))?)?)?)?)?)?(?:[Z]|([-+])(\d\d):(\d\d))?/;$CLJS.Yg=$CLJS.Cf(null);
$CLJS.Zg=$CLJS.Cf($CLJS.Rg($CLJS.Q([new $CLJS.ia(null,4,[new $CLJS.ab(null,"inst","inst",-2008473268,null),function(a){if("string"===typeof a){var b=Xg(a);if($CLJS.u(b)){a=$CLJS.R(b,0,null);var c=$CLJS.R(b,1,null),d=$CLJS.R(b,2,null),e=$CLJS.R(b,3,null),f=$CLJS.R(b,4,null),h=$CLJS.R(b,5,null),k=$CLJS.R(b,6,null);b=$CLJS.R(b,7,null);b=new Date(Date.UTC(a,c-1,d,e,f,h,k)-6E4*b)}else throw Error(["Unrecognized date/time syntax: ",$CLJS.y.a(a)].join(""));return b}throw Error("Instance literal expects a string for its timestamp.");
},$CLJS.Ye,function(a){if("string"===typeof a)return new Sg(a.toLowerCase());throw Error("UUID literal expects a string as its representation.");},new $CLJS.ab(null,"queue","queue",-1198599890,null),function(a){if($CLJS.Gb(a))return $CLJS.Qc($CLJS.mf,a);throw Error("Queue literal expects a vector for its elements.");},new $CLJS.ab(null,"js","js",-886355190,null),function(a){if($CLJS.Gb(a)){var b=[];a=$CLJS.D(a);for(var c=null,d=0,e=0;;)if(e<d){var f=c.N(null,e);b.push(f);e+=1}else if(a=$CLJS.D(a))c=
a,$CLJS.Hb(c)?(a=$CLJS.ye(c),e=$CLJS.ze(c),c=a,d=$CLJS.K(a),a=e):(a=$CLJS.F(c),b.push(a),a=$CLJS.I(c),c=null,d=0),e=0;else break;return b}if($CLJS.Eb(a)){b={};a=$CLJS.D(a);c=null;for(e=d=0;;)if(e<d){var h=c.N(null,e);f=$CLJS.R(h,0,null);h=$CLJS.R(h,1,null);var k=b;f=$CLJS.pe(f);k[f]=h;e+=1}else if(a=$CLJS.D(a))$CLJS.Hb(a)?(d=$CLJS.ye(a),a=$CLJS.ze(a),c=d,d=$CLJS.K(d)):(d=$CLJS.F(a),c=$CLJS.R(d,0,null),d=$CLJS.R(d,1,null),e=b,c=$CLJS.pe(c),e[c]=d,a=$CLJS.I(a),c=null,d=0),e=0;else break;return b}throw Error("JS literal expects a vector or map containing only string or unqualified keyword keys");
}],null),$CLJS.Gc])));