var window=global;var $CLJS=require("./cljs_env");require("./goog.base.js");require("./cljs.core.js");require("./cljs.reader.js");require("./sounds.midi_freq.js");
var $g=function(a,b){return $CLJS.ba[a]=b},ah=function(a,b){var c=Array(a.length-2);$CLJS.Ib(a,0,c,0,2*b);$CLJS.Ib(a,2*(b+1),c,2*b,c.length-2*b);return c},bh=function(){},ch=function(a){if("number"===typeof a)return String.fromCharCode(a);if("string"===typeof a&&1===a.length)return a;throw Error("Argument to char must be a character or number");},dh=function(a){if(null==$CLJS.qa)throw Error("No *print-fn* fn set for evaluation environment");$CLJS.qa.a?$CLJS.qa.a(a):$CLJS.qa.call(null,a)},eh=function(a){var b=
[];for(a=$CLJS.D(a);;)if(null!=a)b.push($CLJS.F(a)),a=$CLJS.I(a);else return b},fh=function(a){if("number"===typeof a&&!isNaN(a)&&Infinity!==a&&parseFloat(a)===parseInt(a,10))return 0===(a&1);throw Error(["Argument must be an integer: ",$CLJS.y.a(a)].join(""));},gh=function(a){return $CLJS.Lc($CLJS.Mb(function(b,c){return $CLJS.oc(b,c,$CLJS.T.f(b,c,0)+1)},$CLJS.Nc($CLJS.Gc),a))},hh=function(a){for(;;){var b=$CLJS.I(a);if(null!=b)a=b;else return $CLJS.F(a)}},ih=function(){var a=$CLJS.pe;return function(){function b(k,
l,m){return new $CLJS.W(null,2,5,$CLJS.X,[$CLJS.ec.f?$CLJS.ec.f(k,l,m):$CLJS.ec.call(null,k,l,m),a.f?a.f(k,l,m):a.call(null,k,l,m)],null)}function c(k,l){return new $CLJS.W(null,2,5,$CLJS.X,[$CLJS.ec.b?$CLJS.ec.b(k,l):$CLJS.ec.call(null,k,l),a.b?a.b(k,l):a.call(null,k,l)],null)}function d(k){return new $CLJS.W(null,2,5,$CLJS.X,[$CLJS.ec.a?$CLJS.ec.a(k):$CLJS.ec.call(null,k),a.a?a.a(k):a.call(null,k)],null)}function e(){return new $CLJS.W(null,2,5,$CLJS.X,[$CLJS.ec.u?$CLJS.ec.u():$CLJS.ec.call(null),
a.u?a.u():a.call(null)],null)}var f=null,h=function(){function k(m,n,p,r){var t=null;if(3<arguments.length){t=0;for(var x=Array(arguments.length-3);t<x.length;)x[t]=arguments[t+3],++t;t=new $CLJS.C(x,0,null)}return l.call(this,m,n,p,t)}function l(m,n,p,r){return new $CLJS.W(null,2,5,$CLJS.X,[$CLJS.yc($CLJS.ec,m,n,p,r),$CLJS.yc(a,m,n,p,r)],null)}k.F=3;k.D=function(m){var n=$CLJS.F(m);m=$CLJS.I(m);var p=$CLJS.F(m);m=$CLJS.I(m);var r=$CLJS.F(m);m=$CLJS.db(m);return l(n,p,r,m)};k.s=l;return k}();f=function(k,
l,m,n){switch(arguments.length){case 0:return e.call(this);case 1:return d.call(this,k);case 2:return c.call(this,k,l);case 3:return b.call(this,k,l,m);default:var p=null;if(3<arguments.length){p=0;for(var r=Array(arguments.length-3);p<r.length;)r[p]=arguments[p+3],++p;p=new $CLJS.C(r,0,null)}return h.s(k,l,m,p)}throw Error("Invalid arity: "+arguments.length);};f.F=3;f.D=h.D;f.u=e;f.a=d;f.b=c;f.f=b;f.s=h.s;return f}()},jh=function(a,b){if("string"===typeof b)return a=a.exec(b),null==a?null:1===$CLJS.K(a)?
$CLJS.F(a):$CLJS.gd(a);throw new TypeError("re-find must match against a string.");},kh=function(a,b){return new $CLJS.fc(null,function(){var c=$CLJS.D(b);return c?$CLJS.U($CLJS.F(c),kh(a,$CLJS.Ff(a,c))):null},null,null)},lh=function(a){if($CLJS.Cb(a))return $CLJS.zb(a,null);a=$CLJS.D(a);if(null==a)return $CLJS.of;if(a instanceof $CLJS.C&&0===a.j){a=a.c;for(var b=a.length,c=$CLJS.Nc($CLJS.of),d=0;;)if(d<b)$CLJS.Mc(c,a[d]),d+=1;else break;return $CLJS.Lc(c)}for(c=$CLJS.Nc($CLJS.of);;)if(null!=a)b=
$CLJS.I(a),c=$CLJS.Mc(c,$CLJS.E(a)),a=b;else return $CLJS.Lc(c)},mh=function(a){for(var b=[],c=arguments.length,d=0;;)if(d<c)b.push(arguments[d]),d+=1;else break;b=0<b.length?new $CLJS.C(b.slice(0),0,null):null;c=$CLJS.Ke.f($CLJS.oa(),$CLJS.ka,!1);dh($CLJS.If(b,c));$CLJS.u($CLJS.pa)?(b=$CLJS.oa(),dh("\n"),b=($CLJS.T.b(b,$CLJS.ja),null)):b=null;return b},nh=function(){},ph=function(a,b){return(null!=a?$CLJS.A===a.ac||(a.pc?0:$CLJS.v(nh,a)):$CLJS.v(nh,a))?oh(a):"string"===typeof a||"number"===typeof a||
a instanceof $CLJS.V||a instanceof $CLJS.ab?b.a?b.a(a):b.call(null,a):$CLJS.If($CLJS.Q([a]),$CLJS.oa())},rh=function(a){return null==a?null:","===a?!0:qh.test(a)},sh=function(a){return null==a?null:!/[^0-9]/.test(a)},th=function(a,b){return function e(d){return new $CLJS.fc(null,function(){for(;;){var f=$CLJS.D(d);if(f){if($CLJS.Hb(f)){var h=$CLJS.ye(f),k=$CLJS.K(h),l=new $CLJS.hc(Array(k));return function(){for(var n=0;;)if(n<k){var p=$CLJS.vb.b(h,n),r=l;if(p instanceof $CLJS.ab||p instanceof $CLJS.V){var t=
ih();var x=t.a?t.a(p):t.call(null,p);t=$CLJS.R(x,0,null);x=$CLJS.R(x,1,null);var B=p instanceof $CLJS.ab?$CLJS.Me:$CLJS.Ge;p=null==t?B.b?B.b(a,x):B.call(null,a,x):$CLJS.N.b("_",t)?B.a?B.a(x):B.call(null,x):p}r.add(p);n+=1}else return!0}()?$CLJS.kc(l.ba(),e($CLJS.ze(f))):$CLJS.kc(l.ba(),null)}var m=$CLJS.F(f);return $CLJS.U(m instanceof $CLJS.ab||m instanceof $CLJS.V?function(){var n=ih();var p=n.a?n.a(m):n.call(null,m);n=$CLJS.R(p,0,null);p=$CLJS.R(p,1,null);var r=m instanceof $CLJS.ab?$CLJS.Me:$CLJS.Ge;
return null==n?r.b?r.b(a,p):r.call(null,a,p):$CLJS.N.b("_",n)?r.a?r.a(p):r.call(null,p):m}():m,e($CLJS.db(f)))}return null}},null,null)}(b)},uh=function(a,b){a=parseInt(a,b);return $CLJS.u(isNaN(a))?-1:a},vh=function(a,b){this.A=a;this.Xb=b;this.ib=0},wh=function(a){for(var b=Array(1),c=0;;)if(1>c)b[c]=null,c+=1;else break;this.Vb=a;this.Ua=b;this.Ca=this.Gb=1},xh=function(a){return null!=a?$CLJS.A===a.Mc?!0:!1:!1},yh=function(a){return $CLJS.Df.b?$CLJS.Df.b(!1,a):$CLJS.Df.call(null,!1,a)},Ch=function(a,
b,c){b=new $CLJS.ia(null,2,[$CLJS.Bg,$CLJS.yg,$CLJS.wg,b],null);a=xh(a)?$CLJS.Ke.s(b,$CLJS.zg,zh(a),$CLJS.Q([$CLJS.ug,Ah(a),$CLJS.vg,Bh(a)])):b;var d=$CLJS.zg.a(a);b=$CLJS.ug.a(a);var e=$CLJS.vg.a(a);d=$CLJS.u(d)?[$CLJS.y.a(d)," "].join(""):null;b=$CLJS.u(b)?["[line ",$CLJS.y.a(b),", col ",$CLJS.y.a(e),"]"].join(""):null;c=$CLJS.yc($CLJS.y,d,b,$CLJS.u($CLJS.u(d)?d:b)?" ":null,c);throw new $CLJS.Re(c,a,null);},Dh=function(a,b){return Ch(a,$CLJS.Cg,$CLJS.Q([$CLJS.wc($CLJS.y,b)]))},Eh=function(a,b){return Ch(a,
$CLJS.xg,$CLJS.Q([$CLJS.wc($CLJS.y,b)]))},Fh=function(a,b){return Ch(a,$CLJS.Ag,$CLJS.Q([$CLJS.wc($CLJS.y,b)]))},Gh=function(a,b,c,d){Dh(a,$CLJS.Q(["The map literal starting with ",yh($CLJS.F(d)),$CLJS.u(b)?[" on line ",$CLJS.y.a(b)," column ",$CLJS.y.a(c)].join(""):null," contains ",$CLJS.K(d)," form(s). Map literals must contain an even number of forms."]))},Hh=function(a,b,c){return Dh(a,$CLJS.Q(["Invalid ",$CLJS.pe(b),": ",c,"."]))},Ih=function(a,b,c){return Dh(a,$CLJS.Q(["Invalid character: ",
c," found while reading ",$CLJS.pe(b),"."]))},Jh=function(a,b){a:{var c=$CLJS.fg instanceof $CLJS.V?$CLJS.fg.Ma:null;switch(c){case "regex":c='#"';break a;case "string":c='"';break a;default:throw Error(["No matching clause: ",$CLJS.y.a(c)].join(""));}}return Fh(a,$CLJS.Q(["Unexpected EOF reading ",$CLJS.pe($CLJS.fg)," starting ",$CLJS.xc($CLJS.y,c,b),"."]))},Kh=function(a,b){return Eh(a,$CLJS.Q(["Invalid digit ",b," in unicode character."]))},Lh=function(a){return Dh(a,$CLJS.Q(["Octal escape sequence must be in range [0, 377]."]))},
Mh=function(a,b){b=function(c){return function f(e){return new $CLJS.fc(null,function(){for(var h=e;;)if(h=$CLJS.D(h)){if($CLJS.Hb(h)){var k=$CLJS.ye(h),l=$CLJS.K(k),m=new $CLJS.hc(Array(l));a:for(var n=0;;)if(n<l){var p=$CLJS.vb.b(k,n),r=$CLJS.R(p,0,null);1<$CLJS.R(p,1,null)&&m.add(r);n+=1}else{k=!0;break a}return k?$CLJS.kc(m.ba(),f($CLJS.ze(h))):$CLJS.kc(m.ba(),null)}m=$CLJS.F(h);k=$CLJS.R(m,0,null);if(1<$CLJS.R(m,1,null))return $CLJS.U(k,f($CLJS.db(h)));h=$CLJS.db(h)}else return null},null,null)}(gh(c))}(b);
return $CLJS.yc($CLJS.y,a,1<$CLJS.K(b)?"s":null,": ",$CLJS.Ff(1,$CLJS.cg.b(new $CLJS.Kc(null,-1,", ",null),b)))},Nh=function(a,b,c){b=$CLJS.pe(b);Dh(a,$CLJS.Q([Mh([String(b.charAt(0)).toUpperCase()+String(b.substr(1)).toLowerCase()," literal contains duplicate key"].join(""),c)]))},Oh=function(a){for(var b=a.Va(null);;)if(rh.a?rh.a(b):rh.call(null,b))b=a.Va(null);else return b},Ph=function(a,b){a=jh(a,b);return $CLJS.R(a,0,null)===b},Th=function(a){if(Ph(Qh,a)){var b=$CLJS.gd(jh(Qh,a));if(null!=(b.a?
b.a(2):b.call(null,2)))a=0;else{a="-"===(b.a?b.a(1):b.call(null,1));b=null!=(b.a?b.a(3):b.call(null,3))?new $CLJS.W(null,2,5,$CLJS.X,[b.a?b.a(3):b.call(null,3),10],null):null!=(b.a?b.a(4):b.call(null,4))?new $CLJS.W(null,2,5,$CLJS.X,[b.a?b.a(4):b.call(null,4),16],null):null!=(b.a?b.a(5):b.call(null,5))?new $CLJS.W(null,2,5,$CLJS.X,[b.a?b.a(5):b.call(null,5),8],null):null!=(b.a?b.a(7):b.call(null,7))?new $CLJS.W(null,2,5,$CLJS.X,[b.a?b.a(7):b.call(null,7),parseInt(b.a?b.a(6):b.call(null,6))],null):
new $CLJS.W(null,2,5,$CLJS.X,[null,null],null);var c=b.a?b.a(0):b.call(null,0);null==c?a=null:(b=parseInt(c,b.a?b.a(1):b.call(null,1)),a=a?-1*b:b,a=$CLJS.u(isNaN(a))?null:a)}}else Ph(Rh,a)?(b=$CLJS.gd(jh(Rh,a)),a=null!=(b.a?b.a(4):b.call(null,4))?parseFloat(b.a?b.a(1):b.call(null,1)):parseFloat(a)):Ph(Sh,a)?(b=$CLJS.gd(jh(Sh,a)),a=b.a?b.a(1):b.call(null,1),b=b.a?b.a(2):b.call(null,2),a=$CLJS.u(jh(/^\+/,a))?a.substring(1):a,a=parseInt(a)/parseInt(b)):a=null;return a},Uh=function(a){if(""===a||!0===
/:$/.test(a)||!0===/^::/.test(a))return null;var b=a.indexOf("/"),c=0<b?a.substring(0,b):null;if(null!=c){b+=1;if(b===$CLJS.K(a))return null;a=a.substring(b);return sh($CLJS.rb(a,0))||""===a||!1!==/:$/.test(c)||"/"!==a&&-1!==a.indexOf("/")?null:new $CLJS.W(null,2,5,$CLJS.X,[c,a],null)}return"/"===a||-1===a.indexOf("/")?new $CLJS.W(null,2,5,$CLJS.X,[null,a],null):null},Vh=function(){return function(){function a(c,d){var e=null;if(1<arguments.length){e=0;for(var f=Array(arguments.length-1);e<f.length;)f[e]=
arguments[e+1],++e;e=new $CLJS.C(f,0,null)}return b.call(this,c,e)}function b(c){return Dh(c,$CLJS.Q(["Unreadable form"]))}a.F=1;a.D=function(c){var d=$CLJS.F(c);c=$CLJS.db(c);return b(d,c)};a.s=b;return a}()},Wh=function(a){return"@"===a||"`"===a||"~"===a},Xh=function(a,b){return Dh(a,$CLJS.Q(["Unmatched delimiter ",b,"."]))},Yh=function(a,b,c){b=1+b;if($CLJS.K(a)!==b)throw Eh(null,$CLJS.Q(["Invalid unicode literal: \\",a,"."]));for(var d=1,e=0;;){if(d===b)return String.fromCharCode(e);var f=uh($CLJS.rb(a,
d),c);if(-1===f)return c=$CLJS.rb(a,d),Eh(null,$CLJS.Q(["Invalid digit ",c," in unicode character \\",a,"."]));e=f+e*c;d+=1}},Zh=function(a){return xh(a)?new $CLJS.W(null,2,5,$CLJS.X,[Ah(a),(Bh(a)|0)-1|0],null):null},ai=function(a){return"#"!==a?"'"!==a?":"!==a?$h.a?$h.a(a):$h.call(null,a):!1:!1:!1},ei=function(a,b,c,d){if($CLJS.zf(c))return Fh(a,$CLJS.Q(["Unexpected EOF while reading start of ",$CLJS.pe(b),"."]));if($CLJS.u($CLJS.u(d)?Wh(c):d))return Ih(a,b,c);d=new $CLJS.ha;for(bi(a,c);;){if(rh(c)||
ai(c)||null==c)return $CLJS.y.a(d);if(Wh(c))return Ih(a,b,c);d.append(ci(a));c=di(a)}},hi=function(a,b,c){b=ci(a);if($CLJS.u(b)){var d=fi.a?fi.a(b):fi.call(null,b);if($CLJS.u(d))return d.f?d.f(a,b,c):d.call(null,a,b,c);bi(a,b);c=gi.f?gi.f(a,b,c):gi.call(null,a,b,c);return $CLJS.u(c)?c:Dh(a,$CLJS.Q(["No dispatch macro for ",b,"."]))}return Fh(a,$CLJS.Q(["Unexpected EOF while reading dispatch character."]))},ii=function(a,b,c,d,e){for(var f=1,h=uh(b,c);;){if(-1===h)return Kh(a,b);if(f!==d){var k=di(a);
var l=rh(k);l||(l=$h.a?$h.a(k):$h.call(null,k),l=$CLJS.u(l)?l:null==k);if($CLJS.u(l))return $CLJS.u(e)?Eh(a,$CLJS.Q(["Invalid unicode literal. Unicode literals should be ",d,"characters long.  ","value suppled is ",f,"characters long."])):String.fromCharCode(h);l=uh(k,c);ci(a);if(-1===l)return Kh(a,k);h=l+h*c;f+=1}else return String.fromCharCode(h)}},ji=function(a){var b=ci(a);if(null!=b){b=ai(b)||Wh(b)||rh(b)?$CLJS.y.a(b):ei(a,$CLJS.Hg,b,!1);var c=b.length;if(1===c)return $CLJS.rb(b,0);if("newline"===
b)return"\n";if("space"===b)return" ";if("tab"===b)return"\t";if("backspace"===b)return"\b";if("formfeed"===b)return"\f";if("return"===b)return"\r";if($CLJS.u(0==b.lastIndexOf("u",0)))return b=Yh(b,4,16),c=b.charCodeAt(),55295<c&&57344>c?(b=c.toString(16),a=Dh(a,$CLJS.Q(["Invalid character literal \\u",b,"."]))):a=b,a;if($CLJS.u(0==b.lastIndexOf("o",0))){--c;if(3<c)return Dh(a,$CLJS.Q(["Invalid octal escape sequence in a character literal:",b,". Octal escape sequences must be 3 or fewer digits."]));
b=Yh(b,c,8);return 255<(b|0)?Lh(a):b}return Dh(a,$CLJS.Q(["Unsupported character: ",b,"."]))}return Fh(a,$CLJS.Q(["Unexpected EOF while reading character."]))},mi=function(a,b,c,d){var e=Zh(c),f=$CLJS.R(e,0,null);e=$CLJS.R(e,1,null);b=null==b?null:ch(b);for(var h=$CLJS.Nc($CLJS.fd);;){var k=Oh(c);if(!$CLJS.u(k)){var l=a,m=f,n=e,p=$CLJS.K(h);Fh(c,$CLJS.Q(["Unexpected EOF while reading ",$CLJS.u(p)?["item ",$CLJS.y.a(p)," of "].join(""):null,$CLJS.pe(l),$CLJS.u(m)?[", starting at line ",$CLJS.y.a(m),
" and column ",$CLJS.y.a(n)].join(""):null,"."]))}if($CLJS.N.b(b,null==k?null:ch(k)))return $CLJS.Lc(h);l=$h.a?$h.a(k):$h.call(null,k);$CLJS.u(l)?(k=l.f?l.f(c,k,d):l.call(null,c,k,d),h=k!==c?$CLJS.ed.b(h,k):h):(bi(c,k),k=ki?ki(c,!0,null,d):li.call(null,c,!0,null,d),h=k!==c?$CLJS.ed.b(h,k):h)}},oi=function(a,b,c){a=mi($CLJS.ig,")",a,c);return null==a||$CLJS.zf($CLJS.D(a))?$CLJS.H:$CLJS.wc(ni,a)},pi=function(a,b,c){return mi($CLJS.hg,"]",a,c)},qi=function(a,b,c){var d=Zh(a);b=$CLJS.R(d,0,null);d=$CLJS.R(d,
1,null);c=mi($CLJS.jg,"}",a,c);var e=$CLJS.K(c),f=kh(2,c),h=lh(f);!fh(e)&&Gh(a,b,d,c);$CLJS.N.b($CLJS.K(h),$CLJS.K(f))||Nh(a,$CLJS.jg,f);if(e<=2*$CLJS.nf)a=eh(c),a=new $CLJS.ia(null,a.length/2,a,null);else a:for(a=eh(c),b=a.length,d=0,e=$CLJS.Nc($CLJS.Ed);;)if(d<b)c=d+2,e=$CLJS.nc(e,a[d],a[d+1]),d=c;else{a=$CLJS.Lc(e);break a}return a},ri=function(a,b){for(var c=function(){var h=new $CLJS.ha;h.append(b);return h}(),d=ci(a);;){if($CLJS.u(function(){var h=rh(d);if(h)return h;h=$h.a?$h.a(d):$h.call(null,
d);return $CLJS.u(h)?h:null==d}())){var e=$CLJS.y.a(c);bi(a,d);var f=Th(e);return $CLJS.u(f)?f:Dh(a,$CLJS.Q(["Invalid number: ",e,"."]))}e=function(){var h=c;h.append(d);return h}();f=ci(a);c=e;d=f}},si=function(a){var b=ci(a);switch(b){case "t":return"\t";case "r":return"\r";case "n":return"\n";case "\\":return"\\";case '"':return'"';case "b":return"\b";case "f":return"\f";case "u":return b=ci(a),-1===parseInt(b|0,16)?Dh(a,$CLJS.Q(["Invalid unicode escape: \\u",b,"."])):ii(a,b,16,4,!0);default:return sh(b)?
(b=ii(a,b,8,3,!1),255<(b|0)?Lh(a):b):Dh(a,$CLJS.Q(["Unsupported escape character: \\",b,"."]))}},ti=function(a){for(var b=new $CLJS.ha,c=ci(a);;){var d=c;if($CLJS.N.b(null,d))return Jh(a,$CLJS.Q(['"',b]));if($CLJS.N.b("\\",d)){d=function(){var f=b;f.append(si(a));return f}();var e=ci(a);b=d;c=e}else{if($CLJS.N.b('"',d))return $CLJS.y.a(b);d=function(){var f=b;f.append(c);return f}();e=ci(a);b=d;c=e}}},ui=function(a,b){b=ei(a,$CLJS.Jg,b,!0);if($CLJS.u(b))switch(b){case "nil":return null;case "true":return!0;
case "false":return!1;case "/":return $CLJS.Gg;default:var c=Uh(b);c=$CLJS.u(c)?$CLJS.Me.b(c.a?c.a(0):c.call(null,0),c.a?c.a(1):c.call(null,1)):null;return $CLJS.u(c)?c:Hh(a,$CLJS.Jg,b)}else return null},vi=function(a){var b=ci(a);if(rh(b))return Dh(a,$CLJS.Q(["A single colon is not a valid keyword."]));b=ei(a,$CLJS.Lg,b,!0);var c=Uh(b);if($CLJS.u($CLJS.u(c)?-1===b.indexOf("::"):c)){var d=c.a?c.a(0):c.call(null,0);c=c.a?c.a(1):c.call(null,1);return":"===$CLJS.rb(b,0)?Hh(a,$CLJS.Lg,b):$CLJS.Ge.b(d,
c)}return Hh(a,$CLJS.Lg,b)},wi=function(a,b,c){b=ki?ki(a,!0,null,c):li.call(null,a,!0,null,c);b=b instanceof $CLJS.V?$CLJS.Cd([b,!0]):b instanceof $CLJS.ab?new $CLJS.ia(null,1,[$CLJS.Ve,b],null):"string"===typeof b?new $CLJS.ia(null,1,[$CLJS.Ve,b],null):b;$CLJS.Eb(b)||Dh(a,$CLJS.Q(["Metadata cannot be ",yh(b),". Metadata must be a Symbol, Keyword, String or Map."]));c=ki?ki(a,!0,null,c):li.call(null,a,!0,null,c);return null!=c&&(c.g&131072||$CLJS.A===c.Qb)?$CLJS.zb(c,$CLJS.Rg($CLJS.Q([$CLJS.Bb(c),
b]))):Dh(a,$CLJS.Q(["Metadata can not be applied to ",yh(c),". ","Metadata can only be applied to IMetas."]))},xi=function(a,b,c){b=mi($CLJS.kg,"}",a,c);c=lh(b);$CLJS.N.b($CLJS.K(b),$CLJS.K(c))||Nh(a,$CLJS.kg,b);return c},yi=function(a){ki?ki(a,!0,null,!0):li.call(null,a,!0,null,!0);return a},zi=function(a,b,c){b=ci(a);b=ei(a,$CLJS.Dg,b,!0);var d=null==b?null:Uh(b);if(null==d)var e=null;else e=$CLJS.R(d,0,null),d=$CLJS.R(d,1,null),e=$CLJS.u(e)?null:d;if($CLJS.u(e)){if("{"===Oh(a)){b=mi($CLJS.Dg,"}",
a,c);!fh($CLJS.K(b))&&Gh(a,null,null,b);c=th($CLJS.y.a(e),kh(2,b));b=kh(2,$CLJS.db(b));$CLJS.N.b($CLJS.K(lh(c)),$CLJS.K(c))||Nh(a,$CLJS.Dg,c);a:for(a=$CLJS.Nc($CLJS.Gc),c=$CLJS.D(c),b=$CLJS.D(b);;)if(c&&b)a=$CLJS.oc(a,$CLJS.F(c),$CLJS.F(b)),c=$CLJS.I(c),b=$CLJS.I(b);else{a=$CLJS.Lc(a);break a}return a}return Dh(a,$CLJS.Q(["Namespaced map with namespace ",b," does not specify a map."]))}return Dh(a,$CLJS.Q(["Invalid value used as namespace in namespaced map: ",b,"."]))},Ai=function(a,b,c){b=ki?ki(a,
!0,null,c):li.call(null,a,!0,null,c);return $CLJS.N.b($CLJS.Kg,b)?Number.NaN:$CLJS.N.b($CLJS.Eg,b)?Number.NEGATIVE_INFINITY:$CLJS.N.b($CLJS.Fg,b)?Number.POSITIVE_INFINITY:Dh(a,$CLJS.Q([["Invalid token: ##",$CLJS.y.a(b)].join("")]))},$h=function(a){switch(a){case '"':return ti;case ":":return vi;case ";":return Bi;case "^":return wi;case "(":return oi;case ")":return Xh;case "[":return pi;case "]":return Xh;case "{":return qi;case "}":return Xh;case "\\":return ji;case "#":return hi;default:return null}},
fi=function(a){switch(a){case "^":return wi;case "{":return xi;case "\x3c":return Vh();case "!":return Bi;case "_":return yi;case ":":return zi;case "#":return Ai;default:return null}},gi=function(a,b,c){b=ki?ki(a,!0,null,c):li.call(null,a,!0,null,c);var d=ki?ki(a,!0,null,c):li.call(null,a,!0,null,c);b instanceof $CLJS.ab||Dh(a,$CLJS.Q(["Invalid reader tag: ",yh("Reader tag must be a symbol"),". Reader tags must be symbols."]));var e=$CLJS.T.b($CLJS.Pg.a(c),b);e=$CLJS.u(e)?e:$CLJS.Gc.a?$CLJS.Gc.a(b):
$CLJS.Gc.call(null,b);if($CLJS.u(e))return e.a?e.a(d):e.call(null,d);c=$CLJS.Yf.a(c);return $CLJS.u(c)?c.b?c.b(b,d):c.call(null,b,d):Dh(a,$CLJS.Q(["No reader function for tag ",yh(b),"."]))},li=function(a){switch(arguments.length){case 1:return Ci($CLJS.Gc,arguments[0]);case 2:return Ci(arguments[0],arguments[1]);case 4:return ki(arguments[0],arguments[1],arguments[2],arguments[3]);default:throw Error(["Invalid arity: ",$CLJS.y.a(arguments.length)].join(""));}},Ci=function(a,b){a=null!=a&&(a.g&64||
$CLJS.A===a.La)?$CLJS.wc(Di,a):a;var c=$CLJS.T.b(a,$CLJS.Ag),d=!$CLJS.Lb(a,$CLJS.Ag);return ki(b,d,c,a)},ki=function(a,b,c,d){try{for(;;){var e=ci(a);if(!rh(e)){if(null==e){if($CLJS.u(b)){b=a;var f=$CLJS.u(null)?Fh(b,$CLJS.Q(["EOF while reading, starting at line ",null,"."])):Fh(b,$CLJS.Q(["EOF while reading."]))}else f=c;return f}if(sh(e)||("+"===e||"-"===e)&&sh(a.pb(null)))return ri(a,e);var h=$h(e);if($CLJS.u(h)){var k=h.f?h.f(a,e,d):h.call(null,a,e,d);if(k!==a)return k}else return ui(a,e)}}}catch(l){if(l instanceof
Error){f=l;if(f instanceof $CLJS.Re){b=f instanceof $CLJS.Re?f.data:null;if($CLJS.N.b($CLJS.yg,$CLJS.Bg.a(b)))throw f;a=$CLJS.Rg($CLJS.Q([new $CLJS.ia(null,1,[$CLJS.Bg,$CLJS.yg],null),b,xh(a)?new $CLJS.ia(null,3,[$CLJS.ug,Ah(a),$CLJS.Ig,Bh(a),$CLJS.zg,zh(a)],null):null]));throw new $CLJS.Re(f.message,a,f);}a=$CLJS.Rg($CLJS.Q([new $CLJS.ia(null,1,[$CLJS.Bg,$CLJS.yg],null),xh(a)?new $CLJS.ia(null,3,[$CLJS.ug,Ah(a),$CLJS.Ig,Bh(a),$CLJS.zg,zh(a)],null):null]));throw new $CLJS.Re(f.message,a,f);}throw l;
}},Ei=function(a){var b=new $CLJS.ia(null,3,[$CLJS.Pg,$CLJS.J($CLJS.Zg),$CLJS.Yf,$CLJS.J($CLJS.Yg),$CLJS.Ag,null],null);return $CLJS.u($CLJS.u(a)?!$CLJS.N.b(a,""):a)?Ci(b,new wh(new vh(a,$CLJS.K(a)))):null},Gi=function(a){if($CLJS.N.b(2,$CLJS.K(a))){var b=$CLJS.F(a);a=$CLJS.F($CLJS.I(a));return function(){var d=$CLJS.Ge.a(b);return d.a?d.a(Fi):d.call(null,Fi)}()+12*a}b=$CLJS.F(a);var c=$CLJS.N.b($CLJS.F($CLJS.I(a)),"#")?1:$CLJS.N.b($CLJS.F($CLJS.I(a)),"b")?-1:null;a=hh(a);return c+function(){var d=
$CLJS.Ge.a(b);return d.a?d.a(Fi):d.call(null,Fi)}()+12*a},Hi=function(a){a=$CLJS.Ge.a($CLJS.y.a(a));return a.a?a.a($CLJS.rf):a.call(null,$CLJS.rf)},Li=function(){var a=$CLJS.Gc,b=null!=a&&(a.g&64||$CLJS.A===a.La)?$CLJS.wc(Di,a):a;a=$CLJS.T.b(b,$CLJS.Bg);var c=$CLJS.T.b(b,Ii);b=$CLJS.T.b(b,Ji);return $CLJS.Cf(new $CLJS.ia(null,4,[$CLJS.Bg,$CLJS.u(a)?a:"sine",Ii,$CLJS.u(c)?"string"===typeof c?Hi(Gi(c)):c:440,Ji,$CLJS.u(b)?b:.25,Ki,2E3],null))},Oi=function(a){var b=$CLJS.J(a),c=null!=b&&(b.g&64||$CLJS.A===
b.La)?$CLJS.wc(Di,b):b;b=$CLJS.T.b(c,$CLJS.Bg);var d=$CLJS.T.b(c,Ii);c=$CLJS.T.b(c,Ji);var e=Mi.createOscillator(),f=Mi.createGain();e.frequency.value=d;e.type=b;f.connect(Mi.destination);f.gain.value=c;e.connect(f);e.start();$CLJS.Nf.B(a,$CLJS.Ke,Ni,e)},Qi=function(a,b){Oi(a);setTimeout(function(){var c=Ni.a($CLJS.J(a));$CLJS.u(c)?(c.stop(),c=$CLJS.Nf.f(a,Pi,Ni)):c=mh.a?mh.a("OSC was not playing!"):mh.call(null,"OSC was not playing!");return c},b)},Ti=function(a){var b=/\./;a="/(?:)/"===$CLJS.y.a(b)?
$CLJS.Pc.b($CLJS.gd($CLJS.U("",$CLJS.Fe.b($CLJS.y,$CLJS.D(a)))),""):$CLJS.gd($CLJS.y.a(a).split(b));if(1<$CLJS.K(a))a:for(;;)if(""===(null==a?null:Ri(a)))a=null==a?null:Si(a);else break a;b=$CLJS.F(a);a=1<$CLJS.K(a)?Ei($CLJS.y.a(hh(a))):0;var c=1<$CLJS.K(b)?$CLJS.F(b):null;c=$CLJS.N.b("b",c)?-1:$CLJS.N.b("#",c)?1:0;var d=$CLJS.y.a(hh(b));b=$CLJS.u(d)?d:b.u?b.u():b.call(null);b=Ei(b);return $CLJS.rb(new $CLJS.W(null,9,5,$CLJS.X,[null,0,2,4,5,7,9,11,12],null),b)+c+12*a},Vi=function(a,b,c,d){d=null!=
d&&(d.g&64||$CLJS.A===d.La)?$CLJS.wc(Di,d):d;d=$CLJS.T.b(d,Ui);d=$CLJS.u(d)?Gi(d):60;b=$CLJS.D(b);for(var e=null,f=0,h=0;;)if(h<f){var k=e.N(null,h);k=d+Ti(k);k=Hi(k);var l=$CLJS.Cf($CLJS.J(a)),m=c;$CLJS.Nf.B(l,$CLJS.Ke,Ii,k);Qi(l,m);h+=1}else if(b=$CLJS.D(b))$CLJS.Hb(b)?(f=$CLJS.ye(b),b=$CLJS.ze(b),e=f,f=$CLJS.K(f)):(k=$CLJS.F(b),e=d+Ti(k),e=Hi(e),f=$CLJS.Cf($CLJS.J(a)),h=c,$CLJS.Nf.B(f,$CLJS.Ke,Ii,e),Qi(f,h),b=$CLJS.I(b),e=null,f=0),h=0;else return null},Wi=function(){for(var a=Li(),b=new $CLJS.W(null,
2,5,$CLJS.X,["1","3"],null),c=$CLJS.Q([Ui,"e5"]),d=null!=c&&(c.g&64||$CLJS.A===c.La)?$CLJS.wc(Di,c):c,e=$CLJS.T.b(d,Ui),f=$CLJS.K(b),h=$CLJS.Fe.b(function(l){return 100*l},0>=f?$CLJS.H:new $CLJS.se(null,0,f,1,null,null,null)),k=0;;)if(k<f)setTimeout(function(l,m,n,p,r,t,x){return function(){return Vi(a,new $CLJS.W(null,1,5,$CLJS.X,[$CLJS.rb(b,l)],null),100,$CLJS.Q([Ui,x]))}}(k,f,f,h,c,d,e),$CLJS.rb(h,k)),k+=1;else return null},Xi=function Xi(a,b,c){var e=a.h-2>>>b&31;if(5<b){b-=5;var f=c.c[e];a=Xi.f?
Xi.f(a,b,f):Xi.call(null,a,b,f);if(null==a&&0===e)return null;c=$CLJS.Tc(c);c.c[e]=a;return c}if(0===e)return null;c=$CLJS.Tc(c);c.c[e]=null;return c};
$CLJS.Md.prototype.Sa=$g(14,function(a,b,c){var d=1<<(b>>>a&31);if(0===(this.H&d))return this;var e=$CLJS.Zb(this.H&d-1),f=this.c[2*e],h=this.c[2*e+1];return null==f?(a=h.Sa(a+5,b,c),a===h?this:null!=a?new $CLJS.Md(null,this.H,$CLJS.Id(this.c,2*e+1,a)):this.H===d?null:new $CLJS.Md(null,this.H^d,ah(this.c,e))):$CLJS.Hd(c,f)?new $CLJS.Md(null,this.H^d,ah(this.c,e)):this});
$CLJS.Od.prototype.Sa=$g(13,function(a,b,c){var d=b>>>a&31,e=this.c[d];if(null!=e){a=e.Sa(a+5,b,c);if(a===e)d=this;else if(null==a)if(8>=this.h)a:{e=this.c;a=e.length;b=Array(2*(this.h-1));c=0;for(var f=1,h=0;;)if(c<a)c!==d&&null!=e[c]?(b[f]=e[c],f+=2,h|=1<<c,c+=1):c+=1;else{d=new $CLJS.Md(null,h,b);break a}}else d=new $CLJS.Od(null,this.h-1,$CLJS.Id(this.c,d,a));else d=new $CLJS.Od(null,this.h,$CLJS.Id(this.c,d,a));return d}return this});
$CLJS.Qd.prototype.Sa=$g(12,function(a,b,c){a=$CLJS.Pd(this.c,this.h,c);return-1===a?this:1===this.h?null:new $CLJS.Qd(null,this.Na,this.h-1,ah(this.c,$CLJS.Yb(a)))});$CLJS.ia.prototype.kb=$g(11,function(a,b){if(0<=$CLJS.yd(this.c,b)){a=this.c.length;var c=a-2;if(0===c)return this.S(null);c=Array(c);for(var d=0,e=0;;){if(d>=a)return new $CLJS.ia(this.i,this.h-1,c,null);$CLJS.N.b(b,this.c[d])?d+=2:(c[e]=this.c[d],c[e+1]=this.c[d+1],e+=2,d+=2)}}else return this});
$CLJS.de.prototype.kb=$g(10,function(a,b){if(null==b)return this.fa?new $CLJS.de(this.i,this.h-1,this.root,!1,null,null):this;if(null==this.root)return this;a=this.root.Sa(0,$CLJS.Za(b),b);return a===this.root?this:new $CLJS.de(this.i,this.h-1,a,this.fa,this.ea,null)});$CLJS.ac.prototype.Ea=$g(9,function(){return this.$(null)});$CLJS.cc.prototype.Ea=$g(8,function(){throw Error("Can't pop empty list");});
$CLJS.W.prototype.Ea=$g(7,function(){if(0===this.h)throw Error("Can't pop empty vector");if(1===this.h)return $CLJS.yb($CLJS.fd,this.i);if(1<this.h-$CLJS.Uc(this))return new $CLJS.W(this.i,this.h-1,this.shift,this.root,this.ga.slice(0,-1),null);var a=$CLJS.Xc(this,this.h-2),b=Xi(this,this.shift,this.root);b=null==b?$CLJS.X:b;var c=this.h-1;return 5<this.shift&&null==b.c[1]?new $CLJS.W(this.i,c,this.shift-5,b.c[0],a,null):new $CLJS.W(this.i,c,this.shift,b,a,null)});
$CLJS.sd.prototype.Ea=$g(6,function(){if($CLJS.u(this.ia)){var a=$CLJS.I(this.ia);return a?new $CLJS.sd(this.i,this.count-1,a,this.la,null):new $CLJS.sd(this.i,this.count-1,$CLJS.D(this.la),$CLJS.fd,null)}return this});$CLJS.zd.prototype.Ea=$g(5,function(){return new $CLJS.W(null,1,5,$CLJS.X,[this.key],null)});$CLJS.ac.prototype.Da=$g(4,function(){return this.first});$CLJS.cc.prototype.Da=$g(3,function(){return null});$CLJS.W.prototype.Da=$g(2,function(){return 0<this.h?this.N(null,this.h-1):null});
$CLJS.sd.prototype.Da=$g(1,function(){return $CLJS.F(this.ia)});$CLJS.zd.prototype.Da=$g(0,function(){return this.w});
var Ri=function Ri(a){if(null!=a&&null!=a.Da)return a.Da(a);var c=Ri[$CLJS.q(null==a?null:a)];if(null!=c)return c.a?c.a(a):c.call(null,a);c=Ri._;if(null!=c)return c.a?c.a(a):c.call(null,a);throw $CLJS.w("IStack.-peek",a);},Yi=function Yi(a){if(null!=a&&null!=a.V)return a.V(a);var c=Yi[$CLJS.q(null==a?null:a)];if(null!=c)return c.a?c.a(a):c.call(null,a);c=Yi._;if(null!=c)return c.a?c.a(a):c.call(null,a);throw $CLJS.w("INext.-next",a);},Zi=function Zi(a,b){if(null!=a&&null!=a.kb)return a.kb(a,b);var d=
Zi[$CLJS.q(null==a?null:a)];if(null!=d)return d.b?d.b(a,b):d.call(null,a,b);d=Zi._;if(null!=d)return d.b?d.b(a,b):d.call(null,a,b);throw $CLJS.w("IMap.-dissoc",a);},Si=function Si(a){if(null!=a&&null!=a.Ea)return a.Ea(a);var c=Si[$CLJS.q(null==a?null:a)];if(null!=c)return c.a?c.a(a):c.call(null,a);c=Si._;if(null!=c)return c.a?c.a(a):c.call(null,a);throw $CLJS.w("IStack.-pop",a);},ni=function ni(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return ni.s(0<c.length?
new $CLJS.C(c.slice(0),0,null):null)};ni.s=function(a){if(a instanceof $CLJS.C&&0===a.j)var b=a.c;else a:for(b=[];;)if(null!=a)b.push($CLJS.E(a)),a=Yi(a);else break a;a=b.length;for(var c=$CLJS.H;;)if(0<a){var d=a-1;c=$CLJS.Oc(c,b[a-1]);a=d}else return c};ni.F=0;ni.D=function(a){return this.s($CLJS.D(a))};
var Pi=function Pi(a){switch(arguments.length){case 1:return Pi.a(arguments[0]);case 2:return Pi.b(arguments[0],arguments[1]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return Pi.s(arguments[0],arguments[1],new $CLJS.C(c.slice(2),0,null))}};Pi.a=function(a){return a};Pi.b=function(a,b){return null==a?null:Zi(a,b)};Pi.s=function(a,b,c){for(;;){if(null==a)return null;a=Pi.b(a,b);if($CLJS.u(c))b=$CLJS.F(c),c=$CLJS.I(c);else return a}};
Pi.D=function(a){var b=$CLJS.F(a),c=$CLJS.I(a);a=$CLJS.F(c);c=$CLJS.I(c);return this.s(b,a,c)};Pi.F=2;var Di=function Di(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return Di.s(0<c.length?new $CLJS.C(c.slice(0),0,null):null)};Di.s=function(a){a=$CLJS.D(a);for(var b=$CLJS.Nc($CLJS.Ed);;)if(a){var c=$CLJS.I($CLJS.I(a));b=$CLJS.oc(b,$CLJS.F(a),$CLJS.F($CLJS.I(a)));a=c}else return $CLJS.Lc(b)};Di.F=0;Di.D=function(a){return this.s($CLJS.D(a))};
var oh=function oh(a){if(null!=a&&null!=a.bc)return a.bc(a);var c=oh[$CLJS.q(null==a?null:a)];if(null!=c)return c.a?c.a(a):c.call(null,a);c=oh._;if(null!=c)return c.a?c.a(a):c.call(null,a);throw $CLJS.w("IEncodeJS.-clj-\x3ejs",a);},$i=function $i(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return $i.s(arguments[0],1<c.length?new $CLJS.C(c.slice(1),0,null):null)};
$i.s=function(a,b){b=null!=b&&(b.g&64||$CLJS.A===b.La)?$CLJS.wc(Di,b):b;var c=$CLJS.T.f(b,$CLJS.Xe,$CLJS.pe),d=function h(f){if(null==f)return null;if(null!=f?$CLJS.A===f.ac||(f.pc?0:$CLJS.v(nh,f)):$CLJS.v(nh,f))return oh(f);if(f instanceof $CLJS.V)return c.a?c.a(f):c.call(null,f);if(f instanceof $CLJS.ab)return $CLJS.y.a(f);if($CLJS.Eb(f)){var k={};f=$CLJS.D(f);for(var l=null,m=0,n=0;;)if(n<m){var p=l.N(null,n),r=$CLJS.R(p,0,null),t=$CLJS.R(p,1,null);p=k;r=ph(r,d);t=h(t);p[r]=t;n+=1}else if(f=$CLJS.D(f))$CLJS.Hb(f)?
(m=$CLJS.ye(f),f=$CLJS.ze(f),l=m,m=$CLJS.K(m)):(l=$CLJS.F(f),m=$CLJS.R(l,0,null),n=$CLJS.R(l,1,null),l=k,m=ph(m,d),n=h(n),l[m]=n,f=$CLJS.I(f),l=null,m=0),n=0;else break;return k}if(null==f?0:null!=f?f.g&8||$CLJS.A===f.Bc||(f.g?0:$CLJS.v(bh,f)):$CLJS.v(bh,f)){k=[];f=$CLJS.D($CLJS.Fe.b(h,f));l=null;for(n=m=0;;)if(n<m)p=l.N(null,n),k.push(p),n+=1;else if(f=$CLJS.D(f))l=f,$CLJS.Hb(l)?(f=$CLJS.ye(l),n=$CLJS.ze(l),l=f,m=$CLJS.K(f),f=n):(f=$CLJS.F(l),k.push(f),f=$CLJS.I(l),l=null,m=0),n=0;else break;return k}return f};
return d(a)};$i.F=1;$i.D=function(a){var b=$CLJS.F(a);a=$CLJS.I(a);return this.s(b,a)};
var qh=/[\s]/,ci=function ci(a){if(null!=a&&null!=a.Va)return a.Va(a);var c=ci[$CLJS.q(null==a?null:a)];if(null!=c)return c.a?c.a(a):c.call(null,a);c=ci._;if(null!=c)return c.a?c.a(a):c.call(null,a);throw $CLJS.w("Reader.read-char",a);},di=function di(a){if(null!=a&&null!=a.pb)return a.pb(a);var c=di[$CLJS.q(null==a?null:a)];if(null!=c)return c.a?c.a(a):c.call(null,a);c=di._;if(null!=c)return c.a?c.a(a):c.call(null,a);throw $CLJS.w("Reader.peek-char",a);},bi=function bi(a,b){if(null!=a&&null!=a.Ub)return a.Ub(a,
b);var d=bi[$CLJS.q(null==a?null:a)];if(null!=d)return d.b?d.b(a,b):d.call(null,a,b);d=bi._;if(null!=d)return d.b?d.b(a,b):d.call(null,a,b);throw $CLJS.w("IPushbackReader.unread",a);},Ah=function Ah(a){if(null!=a&&null!=a.sc)return a.sc(a);var c=Ah[$CLJS.q(null==a?null:a)];if(null!=c)return c.a?c.a(a):c.call(null,a);c=Ah._;if(null!=c)return c.a?c.a(a):c.call(null,a);throw $CLJS.w("IndexingReader.get-line-number",a);},Bh=function Bh(a){if(null!=a&&null!=a.qc)return a.qc(a);var c=Bh[$CLJS.q(null==a?
null:a)];if(null!=c)return c.a?c.a(a):c.call(null,a);c=Bh._;if(null!=c)return c.a?c.a(a):c.call(null,a);throw $CLJS.w("IndexingReader.get-column-number",a);},zh=function zh(a){if(null!=a&&null!=a.rc)return a.rc(a);var c=zh[$CLJS.q(null==a?null:a)];if(null!=c)return c.a?c.a(a):c.call(null,a);c=zh._;if(null!=c)return c.a?c.a(a):c.call(null,a);throw $CLJS.w("IndexingReader.get-file-name",a);};vh.prototype.Va=function(){if(this.Xb>this.ib){var a=this.A.charAt(this.ib);this.ib+=1;return a}return null};
vh.prototype.pb=function(){return this.Xb>this.ib?this.A.charAt(this.ib):null};wh.prototype.Va=function(){var a=this.Ca<this.Gb?this.Ua[this.Ca]:this.Vb.Va(null);this.Ca<this.Gb&&(this.Ca+=1);return null==a?null:ch(a)};wh.prototype.pb=function(){var a=this.Ca<this.Gb?this.Ua[this.Ca]:this.Vb.pb(null);return null==a?null:ch(a)};wh.prototype.Ub=function(a,b){if($CLJS.u(b)){if(0===this.Ca)throw Error("Pushback buffer is full");--this.Ca;return this.Ua[this.Ca]=b}return null};
var Qh=/^([-+]?)(?:(0)|([1-9][0-9]*)|0[xX]([0-9A-Fa-f]+)|0([0-7]+)|([1-9][0-9]?)[rR]([0-9A-Za-z]+)|0[0-9]+)(N)?$/,Sh=/([-+]?[0-9]+)\/([0-9]+)/,Rh=/([-+]?[0-9]+(\.[0-9]*)?([eE][-+]?[0-9]+)?)(M)?/,Bi=function Bi(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return Bi.s(arguments[0],1<c.length?new $CLJS.C(c.slice(1),0,null):null)};Bi.s=function(a){for(;;){var b=a.Va(null);if("\n"===b||"\n"===b||null==b)break}return a};Bi.F=1;
Bi.D=function(a){var b=$CLJS.F(a);a=$CLJS.I(a);return this.s(b,a)};
var Ki=new $CLJS.V(null,"default-dur","default-dur",640662375),aj=new $CLJS.V(null,"success","success",1890645906),Ii=new $CLJS.V(null,"freq","freq",-1855845278),bj=new $CLJS.V(null,"continue","continue",-207346553),cj=new $CLJS.V(null,"unrecognized","unrecognized",301694737),Ui=new $CLJS.V(null,"key","key",-1516042587),dj=new $CLJS.V(null,"error","error",-978969032),Ni=new $CLJS.V(null,"instance","instance",-2121349050),Ji=new $CLJS.V(null,"gain","gain",1350925045),ej=new $CLJS.V(null,"ready-for-input",
"ready-for-input",1830756619);var Fi=new $CLJS.ia(null,7,[new $CLJS.V(null,"c","c",-1763192079),0,new $CLJS.V(null,"d","d",1972142424),2,new $CLJS.V(null,"e","e",1381269198),4,new $CLJS.V(null,"f","f",-1597136552),6,new $CLJS.V(null,"g","g",1738089905),8,new $CLJS.V(null,"a","a",-2123407586),10,new $CLJS.V(null,"b","b",1482224470),12],null),Mi=new AudioContext;$CLJS.Fe.b($CLJS.y,new $CLJS.W(null,5,5,$CLJS.X,[1,2,3,5,6],null));$CLJS.Fe.b($CLJS.y,new $CLJS.W(null,5,5,$CLJS.X,[1,"b3",4,5,"b7"],null));
$CLJS.Fe.b($CLJS.y,new $CLJS.W(null,7,5,$CLJS.X,[1,2,"b3",4,5,"b6","b7"],null));$CLJS.Fe.b($CLJS.y,new $CLJS.W(null,7,5,$CLJS.X,[1,2,"b3",4,5,"b6",7],null));
var fj=$i(new $CLJS.ia(null,5,[aj,function(){return Vi(Li(),new $CLJS.W(null,2,5,$CLJS.X,["1","3"],null),200,$CLJS.Q([Ui,"e5"]))},bj,function(){return Vi(Li(),new $CLJS.W(null,1,5,$CLJS.X,["5.-1"],null),100,$CLJS.Q([Ui,"e5"]))},dj,function(){return Vi(Li(),new $CLJS.W(null,2,5,$CLJS.X,["1","b3"],null),200,$CLJS.Q([Ui,"e5"]))},ej,function(){return Wi()},cj,function(){return Vi(Li(),new $CLJS.W(null,2,5,$CLJS.X,["1","b5"],null),200,$CLJS.Q([Ui,"e5"]))}],null));module.exports={sounds:fj};